services:
  airflow:
    build:
      context: .
      dockerfile_inline: |
        FROM apache/airflow:slim-3.1.6-python3.12
        COPY requirements.txt /opt/airflow/requirements.txt
        RUN pip install --no-cache-dir apache-airflow[postgres]==3.1.6
        RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: True
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: False
      AIRFLOW__LOGGING__MIN_LENGTH_MASKED_SECRET: 0
    env_file:
      - .env
    volumes:
      - .:${AIRFLOW_VAR_AIRFLOW_DAG_HOME:-/opt/airflow/dags/}/data_pipelines_annuaire
      - ${LOCAL_TMP_PATH:-.docker}/tmp:${AIRFLOW_VAR_AIRFLOW_DAG_TMP}
      - ${LOCAL_TMP_PATH:-.docker}/logs:/opt/airflow/logs
      - ${LOCAL_TMP_PATH:-.docker}/scripts:/opt/airflow/scripts:ro
      - ${LOCAL_TMP_PATH:-.docker}/ssh:/home/airflow/.ssh/:ro
    ports:
      - "127.0.0.1:${AIRFLOW_API_PORT:-8080}:8080"
      - "127.0.0.1:${AIRFLOW_LOG_SERVER_PORT:-8793}:8793"
    entrypoint: airflow standalone
    networks:
      - annuaire-network
    container_name: "airflow-${DOCKER_CONTEXT:-ade}-${DOCKER_ENV:-test}"

  postgres:
    image: postgres:16
    user: root
    volumes:
      - ${LOCAL_TMP_PATH:-.docker}/pg-airflow:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "127.0.0.1:${AIRFLOW_POSTGRES_PORT:-5432}:5432"
    networks:
      - annuaire-network
    container_name: "airflow-db-${DOCKER_CONTEXT:-ade}-${DOCKER_ENV:-test}"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - cluster.name=annuaire-search-cluster
      - node.name=annuaire-es-node-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - ELASTIC_USER=${AIRFLOW_VAR_ELASTIC_USER:-elastic}
      - ELASTIC_PASSWORD=${AIRFLOW_VAR_ELASTIC_PASSWORD:-elastic}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${LOCAL_TMP_PATH:-.docker}/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "${AIRFLOW_VAR_ELASTIC_PORT:-9200}:9200"
      - "9300:9300"
    networks:
      - annuaire-network
    container_name: "elasticsearch-${DOCKER_CONTEXT:-ade}-${DOCKER_ENV:-test}"

networks:
  annuaire-network:
